import unittest
from src.process_data import parse_data, preformat
class TestDataParser(unittest.TestCase):
    def test_parsing(self):
        test_data = """Generated by Trading 212 UK Ltd. on 24 September 2024 at 21:00 (UTC).
Deposits PLN 0.00
Withdrawals PLN 0.00
Realised P/L PLN 56.98
Unrealised P/L PLN 490.15
Dividends PLN 0.00
Overnight interest PLN -8.29
Account value PLN 11,696.72"""
        
        result = parse_data((test_data))
        self.assertEqual(result[0]['Date'], '2024-09-01')
        self.assertEqual(float(result[0]['Account_Value']), 11.896)
        # Add more assertions as needed

if __name__ == '__main__':
    unittest.main()
